Selectable items
CS322-SP23/MixMaster pull request #4
Opened 2023-04-09 00:33 UTC by hjwebb01

Base functionality for a selectable drop with 1 example included

2023-04-09 00:56 UTC, ejshakman commented on static/css/styles.css
> -h1
could you put these 2 lines in your code? I may have accidentally removed them when I was fixing the merge conflict
h1
{

2023-04-09 00:58 UTC, ejshakman commented on static/css/styles.css
> +*{
could you please put in some comments for your additions from this line and down?

2023-04-09 01:03 UTC, ejshakman requested changes
Just requesting a small addition to styles.css and some comments on your code in the other files

2023-04-09 01:03 UTC, ejshakman commented on templates/index.html
> +    <div class="container">
could you please put in some comments from this line and down?

2023-04-09 01:03 UTC, ejshakman commented on static/css/styles.css
> -h1
could you put these 2 lines in your code? I may have accidentally removed them when I was fixing the merge conflict
h1
{

2023-04-10 02:10 UTC, Archaversine approved these changes

2023-04-10 02:31 UTC, ejshakman approved these changes
Looks good, thanks!

2023-04-10 02:32 UTC, merged